
try {
    1 / 0;
} catch Exception e {
    throw ValueError() from e;
}
