try {
    1 / 0;
} catch Exception e1 {
    print e1;
} finally {
    print 'finally';
}
